### ISSUE TITLE
Module cannot be seen

### ISSUE THREAD

**Issue by arfeen** [notrinos/FrontHrm#2]
Hi

There is no other place to ask this question so opening an issue here. How do I enable the module, although I extracted the files and placed as directed  but still cannot see the options for HRM.

Is there anything additionally I need to do in FrontAccounting ?

Thanks

**Comment by notrinos** [comment]
Yes, @arfeen, there are still something to do to active a module in FA.
Please post your question here to get further help: http://frontaccounting.com/punbb/viewtopic.php?id=6860
Thank you
