### ISSUE TITLE
Front HRM error

### ISSUE THREAD

**Issue by wkuilder** [notrinos/FrontHrm#7]
Hi I like using your system but are having issue with frontHRM all is grayed our except document expiration when I click on it says "There are no Document Types defined in the system" . How would I fix this ?

Tried manually inserting in the database but still no luck.
![HRM1](https://user-images.githubusercontent.com/28683418/194750680-4be9dbb5-f62d-44a1-8fa8-4900db669f5c.JPG)
![hrm 2](https://user-images.githubusercontent.com/28683418/194750686-7c7088b9-c7d3-441d-8b62-e06e3a6c75ea.JPG)

Thanks Wynand

**Comment by notrinos** [comment]
Hi @wkuilder 

First you should go to Setup -> Access Setup then active all HRM access roles for your user
Second, after give the user access roles this user will have to logout and login again to work with all greyed links.

Phuong

**Comment by wkuilder** [comment]
Thanks Phuong, Very quick response and it now works
